# Configuración de despliegue para Netlify

[build]
  publish = "."
  # No hay build step: este es un sitio estático

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Cabeceras útiles para evitar cachés agresivas en el HTML
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store"
